//@version=5
indicator(title='Candlestick Patterns [DW]', overlay=true)
//by Donovan Wall

//This is a simple study designed to track multiple candlestick patterns. Custom alerts included. 

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//Updates:

//Added engulfing and non-engulfing fractal patterns to the list.

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//Inputs
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

//Toggle Switches
e3i = input(defval=true, title='Enable Three Inside Up and Down Signals')
e3o = input(defval=true, title='Enable Three Outside Up and Down Signals')
estr = input(defval=true, title='Enable Morning and Evening Star Signals')
eeng = input(defval=true, title='Enable Bullish and Bearish Engulfing Signals')
eham = input(defval=true, title='Enable Hammer and Inverted Hammer Signals')
edoji = input(defval=true, title='Enable Doji and Near Doji Signals')
efrac = input(defval=true, title='Enable Fractal Signals')

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//Definitions
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

//Three Inside Up
tiu = e3i and open[2] > close[2] and close[1] > open[1] and close[1] <= open[2] and close[2] <= open[1] and close[1] - open[1] < open[2] - close[2] and close > open and close > close[1] and open > open[1] ? 1 : 0

//Three Inside Down
tid = e3i and close[2] > open[2] and open[1] > close[1] and open[1] <= close[2] and open[2] <= close[1] and open[1] - close[1] < close[2] - open[2] and open > close and close > close[1] and open < open[1] ? 1 : 0

//Three Outside Up
tou = e3o and open[2] > close[2] and close[1] > open[1] and close[1] >= open[2] and close[2] >= open[1] and close[1] - open[1] > open[2] - close[2] and close > open and close > close[1] ? 1 : 0

//Three Outside Down
tod = e3o and close[2] > open[2] and open[1] > close[1] and open[1] >= close[2] and open[2] >= close[1] and open[1] - close[1] > close[2] - open[2] and open > close and close < close[1] ? 1 : 0

//Morning Star
mstar = estr and open[2] > close[2] and (open[2] - close[2]) / (.001 + high[2] - low[2]) > .6 and close[2] > open[1] and open[1] > close[1] and high[1] - low[1] > 3 * (close[1] - open[1]) and close > open and open > open[1] ? 1 : 0

//Evening Star
estar = estr and close[2] > open[2] and (close[2] - open[2]) / (.001 + high[2] - low[2]) > .6 and close[2] < open[1] and close[1] > open[1] and high[1] - low[1] > 3 * (close[1] - open[1]) and open > close and open < open[1] ? 1 : 0

//Bullish Engulfing
bulleng = eeng and open[1] > close[1] and close > open and close >= open[1] and close[1] >= open and close - open > open[1] - close[1] ? 1 : 0

//Bearish Engulfing
beareng = eeng and close[1] > open[1] and open > close and open >= close[1] and open[1] >= close and open - close > close[1] - open[1] ? 1 : 0

//Hammer
ham = eham and high - low > 3 * (open - close) and (close - low) / (.001 + high - low) > 0.6 and (open - low) / (.001 + high - low) > 0.6 ? 1 : 0

//Inverted Hammer
iham = eham and high - low > 3 * (open - close) and (high - close) / (.001 + high - low) > 0.6 and (high - open) / (.001 + high - low) > 0.6 ? 1 : 0

//Fractals
ufract = high[4] < high[2] and high[3] < high[2] and high[1] < high[2] and high < high[2] ? 1 : 0
dfract = low[4] > low[2] and low[3] > low[2] and low[1] > low[2] and low > low[2] ? 1 : 0

//Fractal Ranges
rnga = ufract ? high[2] - low[4] : dfract ? high[4] - low[2] : 0
rngb = ufract ? high[2] - low : dfract ? high - low[2] : 0

//Engulfing Fractals
uen = efrac and ufract and rnga <= rngb ? 1 : 0
den = efrac and dfract and rnga <= rngb ? 1 : 0

//Non Engulfing Fractals
une = efrac and ufract and rnga > rngb ? 1 : 0
dne = efrac and dfract and rnga > rngb ? 1 : 0

//Doji or Near Doji
ndoji = edoji and math.abs(open - close) <= (high - low) * 0.1 ? 1 : 0
ndojicolor = ndoji ? color.orange : na

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//Plots
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

//Three Inside Up Signal
plotchar(tiu, title='Three Inside Up Signal', char='◉', color=color.new(#90EE90, 0), text='3IU', textcolor=color.new(#90EE90, 0), size=size.tiny, location=location.belowbar)

//Three Inside Down Signal
plotchar(tid, title='Three Inside Down Signal', char='◉', color=color.new(#F08080, 0), text='3ID', textcolor=color.new(#F08080, 0), size=size.tiny, location=location.abovebar)

//Three Outside Up Signal
plotchar(tou, title='Three Outside Up Signal', char='◎', color=color.new(#00FF7F, 0), text='3OU', textcolor=color.new(#00FF7F, 0), size=size.tiny, location=location.belowbar)

//Three Outside Down Signal
plotchar(tod, title='Three Outside Down Signal', char='◎', color=color.new(#CD5C5C, 0), text='3OD', textcolor=color.new(#CD5C5C, 0), size=size.tiny, location=location.abovebar)

//Morning Star Signal
plotchar(mstar, title='Morning Star Signal', char='✫', color=color.new(#32CD32, 0), text='MS', textcolor=color.new(#32CD32, 0), size=size.tiny, location=location.belowbar)

//Evening Star Signal
plotchar(estar, title='Evening Star Signal', char='✫', color=color.new(color.red, 0), text='ES', textcolor=color.new(color.red, 0), size=size.tiny, location=location.abovebar)

//Bullish Engulfing Signal
plotchar(bulleng, title='Bullish Engulfing Signal', char='↟', color=color.new(#008000, 0), text='E', textcolor=color.new(#008000, 0), size=size.tiny, location=location.belowbar)

//Bearish Engulfing Signal
plotchar(beareng, title='Bearish Engulfing Signal', char='↡', color=color.new(#B22222, 0), text='E', textcolor=color.new(#B22222, 0), size=size.tiny, location=location.abovebar)

//Hammer Signal
plotchar(ham, title='Hammer Signal', char='╦', color=color.new(color.aqua, 0), text='H', textcolor=color.new(color.aqua, 0), size=size.tiny, location=location.belowbar)

//Inverted Hammer Signal
plotchar(iham, title='Inverted Hammer Signal', char='╩', color=color.new(color.fuchsia, 0), text='H', textcolor=color.new(color.fuchsia, 0), size=size.tiny, location=location.abovebar)

//Non-Engulfing Low Fractal Signal
plotchar(dne, title='Non-Engulfing Low Fractal Signal', char='▵', color=color.new(color.gray, 0), size=size.tiny, location=location.belowbar, offset=-2)

//Non-Engulfing High Fractal Signal
plotchar(une, title='Non-Engulfing High Fractal Signal', char='▿', color=color.new(color.gray, 0), size=size.tiny, location=location.abovebar, offset=-2)

//Engulfing Low Fractal Signal
plotchar(den, title='Engulfing Low Fractal Signal', char='▵', color=color.new(color.white, 0), size=size.tiny, location=location.belowbar, offset=-2)

//Engulfing High Fractal Signal
plotchar(uen, title='Engulfing High Fractal Signal', char='▿', color=color.new(color.white, 0), size=size.tiny, location=location.abovebar, offset=-2)

//Doji or Near Doji Signal
barcolor(ndojicolor, title='Doji Highlights')
bgcolor(ndojicolor, transp=90)

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//Alerts
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

//Three Inside Up Alert
alertcondition(tiu, title='Three Inside Up Pattern', message='Three Inside Up Pattern Formed')

//Three Inside Down Alert
alertcondition(tid, title='Three Inside Down Pattern', message='Three Inside Down Pattern Formed')

//Three Outside Up Alert
alertcondition(tou, title='Three Outside Up Pattern', message='Three Outside Up Pattern Formed')

//Three Outside Down Alert
alertcondition(tod, title='Three Outside Down Pattern', message='Three Outside Down Pattern Formed')

//Morning Star Alert
alertcondition(mstar, title='Morning Star Pattern', message='Morning Star Pattern Formed')

//Evening Star Alert
alertcondition(estar, title='Evening Star Pattern', message='Evening Star Pattern Formed')

//Bullish Engulfing Alert
alertcondition(bulleng, title='Bullish Engulfing Pattern', message='Bullish Engulfing Pattern Formed')

//Bullish Engulfing Alert
alertcondition(beareng, title='Bearish Engulfing Pattern', message='Bearish Engulfing Pattern Formed')

//Hammer Alert
alertcondition(ham, title='Hammer Candle', message='Hammer Candle Formed')

//Inverted Hammer Alert
alertcondition(iham, title='Inverted Hammer Candle', message='Inverted Hammer Candle Formed')

//Non-Engulfing Low Fractal Alert
alertcondition(dne, title='Non-Engulfing Low Fractal', message='Non-Engulfing Low Fractal Formed')

//Non-Engulfing High Fractal Alert
alertcondition(une, title='Non-Engulfing High Fractal', message='Non-Engulfing High Fractal Formed')

//Engulfing Low Fractal Alert
alertcondition(den, title='Engulfing Low Fractal', message='Engulfing Low Fractal Formed')

//Engulfing High Fractal Alert
alertcondition(uen, title='Engulfing High Fractal', message='Engulfing High Fractal Formed')

//Doji Alert
alertcondition(ndoji, title='Doji or Near Doji Candle', message='Doji or Near Doji Candle Formed')
